[package]
name = "posts"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
markdown = "1.0.0"
tera = "1.20.1"
walkdir = "2.5.0"
serde = { version = "1.0.228", features = ["derive"] }
